// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./MainPage.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
} from "./_internal_primitives";
import Input, { InputContext } from "./Input";
import ValidationResultIcon, {
  ValidationResultIconContext,
} from "./ValidationResultIcon";

const styles = [
  {
    type: "default",
    layers: {
      CL61ZqDsmp: {
        none: {
          text: "Cloudflare IP Addres Checker",
        },
      },
      BXyZQ1o9NC: {
        none: {
          role: "img",
          src: require("../assets/cd476409-efa8-4810-b7c8-0068494e85d2@1x.svg"),
          useMask: true,
        },
      },
      VbB9ApfSku: {
        none: {
          role: "img",
          src: require("../assets/432f9af9-794c-4188-8117-7d3751502be6@1x.svg"),
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      WYqSvHwq9n: {
        none: {
          placeholder: "e.g. 103.21.244.0",
        },
      },
      PGiGejg5MR: {
        none: {
          status: "valid",
        },
      },
    },
  },
];

const variantPropTypes = [];

export const MainPageContext = createContext(null);

function MainPage(_props) {
  const defaults = useContext(MainPageContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="B3GMqQbie6"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "B3GMqQbie6",
        scope: "9twmSf6vJZ",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_9twmSf6vJZ_4rY6GQvaMN"}
            key={"4rY6GQvaMN"}
            addSpacing={false}
          >
            {
              <IconPrimitive
                className={"__visly_reset __visly_scope_9twmSf6vJZ_VbB9ApfSku"}
                key={"VbB9ApfSku"}
                useMask={getStyle("VbB9ApfSku", "useMask")}
                src={getStyle("VbB9ApfSku", "src")}
              />
            }
          </ContainerPrimitive>
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_9twmSf6vJZ_7fBam9B1ai"}
            key={"7fBam9B1ai"}
            addSpacing={false}
          >
            {
              <IconPrimitive
                className={"__visly_reset __visly_scope_9twmSf6vJZ_BXyZQ1o9NC"}
                key={"BXyZQ1o9NC"}
                useMask={getStyle("BXyZQ1o9NC", "useMask")}
                src={getStyle("BXyZQ1o9NC", "src")}
              />
            }
          </ContainerPrimitive>
          <TextPrimitive
            className={"__visly_reset __visly_scope_9twmSf6vJZ_CL61ZqDsmp"}
            key={"CL61ZqDsmp"}
            text={getStyle("CL61ZqDsmp", "text")}
          />
          <ContainerPrimitive
            className={"__visly_reset __visly_scope_9twmSf6vJZ_MXvZeJSANT"}
            key={"MXvZeJSANT"}
            addSpacing={false}
          >
            {
              <ContainerPrimitive
                className={"__visly_reset __visly_scope_9twmSf6vJZ_DaLbFtbHmy"}
                key={"DaLbFtbHmy"}
                addSpacing={false}
              >
                {[
                  props.Input === undefined ? (
                    <Input
                      key={"WYqSvHwq9n"}
                      {...getCompositeDefaultProps("WYqSvHwq9n")}
                      className="__visly_reset __visly_scope_9twmSf6vJZ_WYqSvHwq9n"
                    />
                  ) : (
                    <InputContext.Provider
                      key="WYqSvHwq9n-provider"
                      value={{
                        key: "WYqSvHwq9n",
                        className:
                          "__visly_reset __visly_scope_9twmSf6vJZ_WYqSvHwq9n",
                        ...getCompositeDefaultProps("WYqSvHwq9n"),
                      }}
                    >
                      {props.Input}
                    </InputContext.Provider>
                  ),
                  <SpacerPrimitive
                    className={
                      "__visly_reset __visly_scope_9twmSf6vJZ_9kw1TdkdF3"
                    }
                    key={"9kw1TdkdF3"}
                  />,
                  props.ValidationResultIcon === undefined ? (
                    <ValidationResultIcon
                      key={"PGiGejg5MR"}
                      {...getCompositeDefaultProps("PGiGejg5MR")}
                      className="__visly_reset __visly_scope_9twmSf6vJZ_PGiGejg5MR"
                    />
                  ) : (
                    <ValidationResultIconContext.Provider
                      key="PGiGejg5MR-provider"
                      value={{
                        key: "PGiGejg5MR",
                        className:
                          "__visly_reset __visly_scope_9twmSf6vJZ_PGiGejg5MR",
                        ...getCompositeDefaultProps("PGiGejg5MR"),
                      }}
                    >
                      {props.ValidationResultIcon}
                    </ValidationResultIconContext.Provider>
                  ),
                ]}
              </ContainerPrimitive>
            }
          </ContainerPrimitive>
        </>
      )}
    </RootPrimitive>
  );
}

MainPage.Input = Input;
MainPage.ValidationResultIcon = ValidationResultIcon;
MainPage.__variants = [];

export default MainPage;
